# Base image
FROM python:3.12-slim

# Set working directory inside container
WORKDIR /app

# Copy the backend folder into /app
COPY backend/ ./backend

# Install dependencies
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Expose the port
EXPOSE 8000

# Run the app
CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
