# Dockerfile.frontend
FROM node:20-alpine

WORKDIR /app

# Copia package.json e package-lock.json
COPY frontend/package*.json ./

# Instala dependências
RUN npm install

# Copia todo o frontend
COPY frontend/ .

# Expõe porta do frontend
EXPOSE 3000

# Comando para rodar o React em modo dev
CMD ["npm", "start"]
